-
  name: Copy and Unzip BRMS data on Target Server
  become: true
  hosts: all
  vars:
    host_user: suyash
    target_user: brms
  tasks:
    - name: Copy BRMS Data
      copy:
        src: /home/{{ host_user }}/test.txt
        dest: /home/{{ target_user }}/
        remote_src: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"