-
  name: Copy and Unzip BRMS data on Target Server
  hosts: all
  become: true
  vars:
    host_user: suyash
    target_user: brms
  tasks:
    - name: Copy BRMS Data
      copy:
        src: /home/{{ host_user }}/test.txt
        dest: /home/{{ target_user }}/test.sh
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
      delegate_to: 192.168.56.60
